# cluster_config.yml - cluster configuration
__default__:
    account: ctbrowngrp
    partition: bmm
    job-name: "{rule}.w{wildcards}"
    logdir: "/home/ntpierce/2020-function-smash/slurm-logs"

sourmash_sketch:
    account: ctbrowngrp
    partition: low2
    job-name: "{rule}.w{wildcards}"
    logdir: "/home/ntpierce/2020-function-smash/slurm-logs/"

sourmash_sketch_chunks:
    account: ctbrowngrp
    partition: low2
    job-name: "{rule}.w{wildcards}"
    logdir: "/home/ntpierce/2020-function-smash/slurm-logs/"

